server:
  port: 80
  context-path: /spring-boot-admin
  session:
    timeout: 1800
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/spring-boot-admin
    username: root
    password: qubo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
  aop:
    proxy-target-class: true
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100MB
custom:
  projectName: spring-boot-admin
  root-path: C:\\${custom.projectName}
  avatar-path: ${custom.root-path}\\avatar
  attachment-path: ${custom.root-path}\\attachment
  ueditor-path: ${custom.attachment-path}\\ueditor
  icon-path: ${custom.attachment-path}\\icon